// SPDX-License-Identifier: MIT
package io.github.redpanda4552.HifumiBot.util;

import io.github.redpanda4552.HifumiBot.HifumiBot;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.entities.Member;
import net.dv8tion.jda.api.entities.Message;
import net.dv8tion.jda.api.entities.User;

public class EmbedUtil {

  public static EmbedBuilder newFootedEmbedBuilderForFilters() {
    return newFootedEmbedBuilder(null, HifumiBot.getSelf().getJDA().getSelfUser().getAvatarUrl());
  }

  public static EmbedBuilder newFootedEmbedBuilder(Message msg) {
    if (msg.getMember() != null) {
      return EmbedUtil.newFootedEmbedBuilder(msg.getMember());
    } else {
      return EmbedUtil.newFootedEmbedBuilder(msg.getAuthor());
    }
  }

  public static EmbedBuilder newFootedEmbedBuilder(Member sender) {
    return newFootedEmbedBuilder(
        sender.getEffectiveName(), sender.getUser().getEffectiveAvatarUrl());
  }

  public static EmbedBuilder newFootedEmbedBuilder(User sender) {
    return newFootedEmbedBuilder(sender.getName(), sender.getEffectiveAvatarUrl());
  }

  private static EmbedBuilder newFootedEmbedBuilder(String displayName, String avatarUrl) {
    EmbedBuilder eb = new EmbedBuilder();
    StringBuilder sb =
        new StringBuilder(
            "This message was automatically generated by "
                + HifumiBot.getSelf().getJDA().getSelfUser().getName());

    if (displayName != null) {
      sb.append(", at the instruction of ");
      sb.append(displayName);
    }

    sb.append(".");
    return eb.setFooter(sb.toString(), avatarUrl);
  }
}
