name: Java CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

# TODO - tests of some sort

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build Docker Image
        run: docker build .